spring:
  application:
    name: forex-service
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    showSql: true
  data:
    jpa.repositories.bootstrapMode: default
  h2:
    console.enabled: true
server:
  port: 8000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  
