spring:
  application:
    name: currency-conversion-service
server:
  port: 8100

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#forex-service:
#  ribbon:
#    listOfServers: localhost:8000,localhost:8001
